name: build-release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, linux-musl, darwin, windows]
        arch: [386, amd64, arm, arm64]
        exclude:
          - os: darwin
            arch: 386
          - os: darwin
            arch: arm
          - os: windows
            arch: arm
          - os: windows
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: '1.23.x'

      - name: Build
        run: go build -o gotempl${{ matrix.os == 'windows' && '.exe' || '' }} .
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os == 'linux-musl' && 'linux' || matrix.os }}
          CGO_ENABLED: ${{ matrix.os == 'linux-musl' && '0' || '1' }}

      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gotempl${{ matrix.os == 'windows' && '.exe' || '' }}
          asset_name: gotempl-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          tag: ${{ github.ref }}
          overwrite: yes
