name: run-test-suite

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@main

      - name: setup@go
        uses: actions/setup-go@main
        with:
          go-version: '1.17.x'

      - name: deps@go
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: build@go
        run: go build .

      - name: check@go
        run: |
          go vet .
          golint .

      - name: test@go
        run: go test -v .
