name: run-test-suite

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@main

      - name: setup@go
        uses: actions/setup-go@main
        with:
          go-version: '1.23.x'

      - name: build@go
        run: go build .

      - name: lint@go
        uses: golangci/golangci-lint-action@master

      - name: test@go
        run: go test -v .
